### ISSUE TITLE
MAC Address change will make the module report MAC Error.

### ISSUE THREAD

**Issue by ohmsai** [Wiznet/WIZ550S2E#10]
FW is written for default MAC address provided by WIZNET, if you change the MAC Address, you will need to change the FW to take care of this. 

/\* Check MAC Address */
check_mac_address();

This call - check_mac_address() will need to modified.

See suggested change below,, 0xAA, 0xBB, 0xCC should be reflective of your mac address prefix assigned to you.
code fragment that needs to changed shown below

if(s2e_packet.network_info_common.mac[0] != 0xaa || s2e_packet.network_info_common.mac[1] != 0xBB || s2e_packet.network_info_common.mac[2] != 0xCC) {
        printf("Input MAC ? ");

//================================
Make a change to the ConfigData.c

void set_S2E_Packet_to_factory_value()
{
//
...
// enter your default MAC ID you want to reset for your module.
    s2e_packet.network_info_common.mac[0] = 0xAA;
    s2e_packet.network_info_common.mac[1] = 0xBB;
    s2e_packet.network_info_common.mac[2] = 0xCC;
    s2e_packet.network_info_common.mac[3] = 0xDD;
    s2e_packet.network_info_common.mac[4] = 0xEE;
    s2e_packet.network_info_common.mac[5] = 0xFF;
//
...
//
}

**Comment by Ricky-Kwon** [comment]
thanks.
