### ISSUE TITLE
Web client

### ISSUE THREAD

**Issue by K-mont** [Wiznet/WIZ550S2E#11]
Hello,

Can I ask you, is it possible send POST (GET) reguest to the web server form WIZ550S2E module?

Thanks

**Comment by ghost** [comment]
Hello, K-mont


WIZ550S2E is also available if you modify the firmware.

However, there is WIZ550Web optimized for HTTP and Web.
Please refer to the links below.
[https://github.com/Wiznet/WIZ550web](url)
[http://wizwiki.net/wiki/doku.php?id=products:wiz550web:start](url)


Thank you.
