### ISSUE TITLE
a mistake ???

### ISSUE THREAD

**Issue by xuruidong** [Wiznet/WIZ550S2E#12]
In file "src/Internet/httpServer.c",  at line 250, function "get_http_uri_name",    return a address on stack ???

Maybe, I am wrong, please tell me the reason, thank you.

**Comment by OpusK** [comment]
These functions are separated by #ifdef __OLD__.
The currently used function takes a buf pointer as an argument and saves it.

Uint8_t get_http_uri_name (uint8_t * uri, uint8_t * uri_buf);

The code is ioLibrary code and I will ask the related team to delete the unused code.
