### ISSUE TITLE
After update no UART comunication

### ISSUE THREAD

**Issue by K-mont** [Wiznet/WIZ550S2E#2]
Hello,
I try compile the Firmware projects for WIZ550S2E, everything was OK. After update to module one status LED is blinking and if I send some command via SERIAL then second status LED is on for cca 1sec and then is off and no answer from module. If I update back to version 1.0.0 then communication is OK.
Can You help me with this??
Thanks
Best Regards

**Comment by bingdo** [comment]
Dear K-mont

How to update FW? Did you use Configuration tool or Flash magic?
Please let me know your update process in detail.

Thanks.

**Comment by K-mont** [comment]
Hello Bingdo,

I build project like this:

the order of compile.
1. lpc_chip_11exx.
2. wiznet_s2e_wiz550s2e_board.
3. WIZ550S2E_App

Than I load WIZ550S2E_App.bin file on TFTP server on my PC. Connect module to LAN, open WIZnet_Configuration_Tool, push the button search the module , push the button F/W Uploading, config the TFTP server and confirm update....  WIZnet_Configuration_Tool writes a successful update.

Best Regards

**Comment by bingdo** [comment]
I have tested your update process.
After update, the target is normal. Please refer to my attached files.

Thanks.

![2015-06-08_wiz550s2e](https://cloud.githubusercontent.com/assets/7875347/8029479/9c10d950-0df8-11e5-8a6a-3a03048d07fe.jpg)
![2015-06-08_wiz550s2e2](https://cloud.githubusercontent.com/assets/7875347/8029480/a069f20c-0df8-11e5-8c70-757e52aacf0e.jpg)
![2015-06-08_wiz550s2e3](https://cloud.githubusercontent.com/assets/7875347/8029482/a49a2770-0df8-11e5-9c7d-404b6c6ddf08.jpg)

**Comment by K-mont** [comment]
I know what the problem is, when I have set as TCP client mode on module than communication works, but when it is mixed TCP mode than not working.

**Comment by bingdo** [comment]
I changed Working Mode to TCP Mixed. It's normal.
Thanks.
![2015-06-08_wiz550s2e4](https://cloud.githubusercontent.com/assets/7875347/8030471/21f2b864-0e02-11e5-9e7a-a568c89728d3.jpg)

**Comment by K-mont** [comment]
OK, it is working when I switch to TCP mode and switch back to TCP mixed mode.

I have one question, is in this firmware support this function "AT + FDNS = Domain_Name support"? Cause I need to be connected from the module on more the TCP servers gradually via DNS name. If I type this command now (like "AT+FDNS=www.google.com") then module is freeze, status LED is still ON and module must be disconnect from power supply.

Thanks.

**Comment by bingdo** [comment]
I have tested AT+FDNS command. Please refer to my attached file.
All commands should be terminated with CR(0x0D), LF(0x0A).

Thanks.
![2015-06-08_wiz550s2e5](https://cloud.githubusercontent.com/assets/7875347/8047371/61a52f64-0e7f-11e5-8557-d2a8e24ead04.jpg)

**Comment by K-mont** [comment]
Hello,
I try it again, but still the same. If I send command AT+FDNS=www.google.com$0d$0a then module answer the IP address, but stay freeze. If I send next other command than no answer and status LED is not blinking. See the attached file.
![terminal](https://cloud.githubusercontent.com/assets/6994820/8052789/056fcbee-0e8b-11e5-8410-2696865c387d.png)
 Is there some sequence of commands? Can You write me step by step commands how I find the IP address from DNS name and then how I connect to the IP and send some data?
In my opinion It is as follows:
1.+++
2.AT+FDNS=www.google.com$0d$0a
3.AT+OPEN=C,,173.194.116.240,3000$0d$0a
4.AT+NSEND=0,7$0d$0a
5.HELLO$0d$0a
6.AT+NCLOSE=0$0d$0a
7.AT+MDATA$0d$0a

Why is not possible in client mode comunicate after connect like sever mode ( without these command "AT+NSEND=0,7$0d$0a")? I always have to first send the length of sending data and then  the data.

Thanks

**Comment by bingdo** [comment]
I tested again but I didn't find a problem.
Please refer to my attached file.
You can use a configuration tool to query DNS. And use TCP Client or TCP Mixed.
If there is data on a serial port, WIZ550S2E will transfer data to a server continuously.

Thanks.

![2015-06-08_wiz550s2e7](https://cloud.githubusercontent.com/assets/7875347/8120779/22137ad4-10de-11e5-9d70-e4381b929d1e.jpg)

**Comment by K-mont** [comment]
OK, and if I want connect to SERVER1 , send some data, then about 1 min later connect to SERVER2 , send some data and the next 1 min connect to SERVER3 a send some data.... How can I do it?

**Comment by K-mont** [comment]
It would be possible to add a command that could be overwrite HOST IP or DOMAIN in DNS?
Then you would edit the SERVER IP ADDRESS  before sending data.

**Comment by bingdo** [comment]
When you send some data to multiple server, refer to http://wizwiki.net/wiki/doku.php?id=products:wiz550s2e:wiz550s2e_tutorial_en:exam3

You can use the following command to overwrite Host IP.
AT+FDNS=www.google.com\r\n
AT+MSAVE\r\n
http://wizwiki.net/wiki/doku.php?id=products:wiz550s2e:wiz550s2epg_kr#wiz550s2e_programmer_s_guide

Thanks.

**Comment by K-mont** [comment]
Hello,
I tested this commands :
AT+FDNS=www.google.com\r\n
AT+MSAVE\r\n
but it dont work, the module is freeze after send AT+FDNS= command.

I try downgrade Firmware to 1.0.0 and there is not working AT+FDNS= command only AT+FDNS, but it works fine. After sending AT+FDNS command the module send me back IP and AT+MOVE command overwrite the Host IP.
Is in actual firmware version (1.0.1) something changed or I made some mistake in sending the commands? because with new FW is module still freeze and with old one 1.0.0 is OK.

Please refer to my attached file.

![fw100](https://cloud.githubusercontent.com/assets/6994820/8292635/0f7791fc-1931-11e5-8633-fbb603991db1.png)
![fw101](https://cloud.githubusercontent.com/assets/6994820/8292636/0f7b888e-1931-11e5-839e-11f5e8e1fa0a.png)

Thanks

**Comment by bingdo** [comment]
I tested FW ver1.0.1 but it's normal.
I have attached my screen image.
Thanks.
![2015-06-08_wiz550s2e9](https://cloud.githubusercontent.com/assets/7875347/8295876/fe1caf7a-1983-11e5-8aa3-3a641d35a9f6.jpg)

**Comment by K-mont** [comment]
I t is possible that the faulty module? It is possible to erase all the memory and upload it again?
I mean whether it is somewhere download the bootloader and application software or can you send me your full flash and I programmed it using by Flash Magic or ...

Thanks

**Comment by bingdo** [comment]
Actually I have no idea.
Please download FW by https://github.com/Wiznet/WIZ550S2E again.
If you have other target, please carry out comparison test.

Thanks.

**Comment by K-mont** [comment]
Hello,
I've bought two new modules do I update the firmware 1.0.1 and it's always the same. When I send the command "+++" get responses "[W,0] [S,0]" and when I send the command "AT+FDNS=www.google.com" then Booth module freezes and does not respond anymore on any instructions.

I try update firmware by WIZnet_Configuration_Tool and by FlashMagic and it is tha same.

Thanks

**Comment by bingdo** [comment]
What is your DNS Server IP? Is it available?
Please attach a screen shot of WIZnet Configuration Tool.
And add a camera capture screen of your HW connection.

Thanks.

**Comment by K-mont** [comment]
Please refer to my attached files
I use for communication USB/RS232 converter "UB232R".
![v100](https://cloud.githubusercontent.com/assets/6994820/8501174/41c3dbdc-21a3-11e5-9993-934e63577fb5.png)
![v101](https://cloud.githubusercontent.com/assets/6994820/8501177/48162f12-21a3-11e5-854e-3c13f213e709.png)
![connection](https://cloud.githubusercontent.com/assets/6994820/8501207/80b5b568-21a3-11e5-8df2-b064997e1c9e.JPG)

Best Regards

**Comment by bingdo** [comment]
I guess there is some noise in your UART connection.
Try to test again after removing unnecessary connection.
I recommend you should use UART2USB interface like attatched file.
Or use WIZ550S2E RS232C interface board.
Working is normal.

Thanks.
![uart2usbinterface](https://cloud.githubusercontent.com/assets/7875347/8514041/4d0f09e0-23be-11e5-825c-6d097c38a7f8.JPG)
![2015-07-06_uart2usbinterface](https://cloud.githubusercontent.com/assets/7875347/8514042/5287ac42-23be-11e5-819c-993c735a09d3.jpg)
![rs232cinterfaceboard](https://cloud.githubusercontent.com/assets/7875347/8514045/737cb5a0-23be-11e5-94bd-20dba69cb719.JPG)
![2015-07-06_rs232cinterfaceboard](https://cloud.githubusercontent.com/assets/7875347/8514043/5f3c0b36-23be-11e5-9fae-e728666531fd.jpg)

**Comment by K-mont** [comment]
Hello, 
I tried to shorten the wires from the module to the USB / RS232 converters, I tried another USB / RS232 converters, I tried to connect the module directly to the ATmega644, but still when I send a command AT+FDNS=www.google.com then module send me a reply IP address and FREEZES! There will be some bugs in the program because version 1.0.0 works and module dont freeze. Could you send me your .bin file to (kmont@orangemail.sk), whether I can try it?
Thanks very much

**Comment by bingdo** [comment]
Please refer to https://github.com/Wiznet/WIZ550S2E/releases/tag/v1.0.1

Thanks.

**Comment by bingdo** [comment]
I have found a problem in LPCXpresso.
I used the version 7.5.0 of LPCXpresso.
But there is a problem in upper version.
I recommend you have to use the 7.5.0 version.
Refer to https://www.lpcware.com/lpcxpresso/downloads/windows

Thanks.
