### ISSUE TITLE
Can´t compile WIZ550S2E v 1.1.4

### ISSUE THREAD

**Issue by K-mont** [Wiznet/WIZ550S2E#28]
Hello,
Can You help me with compile problem :

Building target: WIZ550S2E_App.axf
Invoking: MCU Linker
arm-none-eabi-gcc -nostdlib -Xlinker -Map="WIZ550S2E_App.map" -Xlinker --gc-sections -Xlinker --allow-multiple-definition -mcpu=cortex-m0 -mthumb -T "WIZ550S2E.ld" -L ../linkscripts &Heap:Default;Post Data;Default&Stack:Default;End;Default -o "WIZ550S2E_App.axf"  ./src/netutil/netutil.o  ./src/callback/dhcp_cb.o  ./src/S2E/S2E.o  ./src/PlatformHandler/eepromHandler.o ./src/PlatformHandler/sspHandler.o ./src/PlatformHandler/timerHandler.o ./src/PlatformHandler/uartHandler.o  ./src/Internet/httpServer/httpParser.o ./src/Internet/httpServer/httpServer.o ./src/Internet/httpServer/httpUtil.o  ./src/Internet/TFTP/netutil.o ./src/Internet/TFTP/tftp.o  ./src/Internet/SNTP/sntp.o  ./src/Internet/SNMP/snmp.o ./src/Internet/SNMP/snmp_custom.o  ./src/Internet/MQTT/MQTTPacket/src/MQTTConnectClient.o ./src/Internet/MQTT/MQTTPacket/src/MQTTConnectServer.o ./src/Internet/MQTT/MQTTPacket/src/MQTTDeserializePublish.o ./src/Internet/MQTT/MQTTPacket/src/MQTTFormat.o ./src/Internet/MQTT/MQTTPacket/src/MQTTPacket.o ./src/Internet/MQTT/MQTTPacket/src/MQTTSerializePublish.o ./src/Internet/MQTT/MQTTPacket/src/MQTTSubscribeClient.o ./src/Internet/MQTT/MQTTPacket/src/MQTTSubscribeServer.o ./src/Internet/MQTT/MQTTPacket/src/MQTTUnsubscribeClient.o ./src/Internet/MQTT/MQTTPacket/src/MQTTUnsubscribeServer.o  ./src/Internet/MQTT/MQTTClient.o ./src/Internet/MQTT/mqtt_interface.o  ./src/Internet/FTPServer/ftpd.o  ./src/Internet/FTPClient/ftpc.o  ./src/Internet/DNS/dns.o  ./src/Internet/DHCP/dhcp.o  ./src/Ethernet/W5500/w5500.o  ./src/Ethernet/socket.o ./src/Ethernet/wizchip_conf.o  ./src/Configuration/ConfigData.o ./src/Configuration/ConfigMessage.o  ./src/ATcmd/library/sockutil.o ./src/ATcmd/library/util.o  ./src/ATcmd/atcmd.o ./src/ATcmd/cmdrun.o  ./src/aeabi_romdiv_patch.o ./src/cr_startup_lpc11exx.o ./src/crp.o ./src/main.o ./src/sysinit.o   -lwiznet_s2e_wiz550s2e_board -llpc_chip_11exx
/bin/sh: Heap:Default: command not found
/bin/sh: Post: command not found
/bin/sh: Default: command not found
/bin/sh: Stack:Default: command not found
/bin/sh: End: command not found
c:/nxp/lpcxpresso_7.5.0_254/lpcxpresso/tools/bin/../lib/gcc/arm-none-eabi/4.8.4/../../../../arm-none-eabi/bin/ld.exe: Linker CRP Enabled, but no CRP_WORD provided within application
c:/nxp/lpcxpresso_7.5.0_254/lpcxpresso/tools/bin/../lib/gcc/arm-none-eabi/4.8.4/../../../../arm-none-eabi/bin/ld.exe: warning: cannot find entry symbol ResetISR; defaulting to 00006000
collect2.exe: error: ld returned 1 exit status
/bin/sh: Default: command not found
make: *** [WIZ550S2E_App.axf] Error 127

Best Regards

**Comment by Ricky-Kwon** [comment]
This occurs according to the project settings.

See the following link.
https://github.com/Wiznet/WIZ550S2E/pull/24 

The easiest way is to download the latest project and overwrite the v1.1.4 source file.
