### ISSUE TITLE
Implement the 3964R DUST Protocoll

### ISSUE THREAD

**Issue by hermanthegerman2** [Wiznet/WIZ550S2E#4]
Is it possible to programm a 3964R DUST Protocoll to the WIZ550S2E?
Description of the protocoll: https://de.wikipedia.org/wiki/3964R
Fragments of C/C++ Code: https://www.c-plusplus.net/forum/42820-full

**Comment by bingdo** [comment]
Hi.

Sorry, there is no example about 3964R protocol. 
Actually, I don't know 3964R. But if 3964R is an application protocol, I think you can work porting.

Thanks.
