### ISSUE TITLE
Change Remote port

### ISSUE THREAD

**Issue by K-mont** [Wiznet/WIZ550S2E#6]
Hello,
Can I ask you if is possible change the REMOTE PORT via AT command? 
Because, If I send command "AT+FDNS=xxxxxx" then returned IP address is automatically entered into HOST IP  - It is OK 
But if I want to change the remote port it must do via config tools.
I need send data to 3 different servers with different ports:
AT+FDNS=xxxxxx   port xxxx
AT+FDNS=yyyyy   port yyyy
AT+FDNS=zzzzzz   port zzzz

Thanks For your help
Best Regards

**Comment by bingdo** [comment]
Dear K-mont

Sorry, currently there is no AT command to get/set Remote Port. If you need some function, you can implement that function by changing the open source.
https://github.com/Wiznet/WIZ550S2E

Thanks.
