### ISSUE TITLE
Request to new command

### ISSUE THREAD

**Issue by javakys** [Wiznet/WIZ550S2E#8]
Hello,

One of my customers wanted to change the connection mode, for example from Server mode to Client mode, or the destination IP and port number in command mode and then let WIZ550S2E try to connect with information he changed when I come out to data mode.
But it looks impossible because WIZ550S2E doesn't have any command for this.

Please implement new command for this.

Thank you.

**Comment by Ricky-Kwon** [comment]
Hi.

I confirmed your request.

Your list of request is as below
1. ```
   Change the working mode in AT command
   ```
2. ```
   Change the host IP, and Port in AT command
   ```

So, I add ‘AT+NMODE’  command. 

Detail is as below

AT+NMODE=<working mode>,<source port>,<destination ip>,<destination port>

< working mode> = S : TCP Server, C : TCP Client, M : TCP Mixed, U : UDP

<source port> = WIZ550S2E Port Number

<destination IP> = Destination IP Address

<destination Port> =Destination Port Number

I will update the above information in the wiki page. 

And ‘AT+MSAVE’ command is not listed in the wiki page . it is to store the network information set in ‘AT+NSET’. keep it in mind.

Finally, I was able to find a bug in a while executing your request. and fix it.

Thank you.
