### ISSUE TITLE
Socket does not stay open for more than 2 to 3 seconds.

### ISSUE THREAD

**Issue by ohmsai** [Wiznet/WIZ550S2E#9]
I am using FW Version 1.03 and older versions. By default the device does not connect to a socket say 5000 and communicate. I am using the Development board with a WIZ550S2E module. When entering the AT Mode, I am able to open a socket, and receive data from the Ethernet port. When I close the AT+MDATA comms, I cant send data to the ethernet side. Putty closes the connection, on RAW Socket comms or TELNET to port 5000.

if the Module is a Serial to Ethernet Device (Serial TTL / RS232 / RS485/422) it should start to function like one from power up after the necessary initialization.
(Surely I am missing something.. my experience with WIZNET has been very satisfactory.)

**Comment by ohmsai** [comment]
Connection stays if the Password is removed. The Connection password was an Item I missed. Sorry for any confusion.
Moderator, kindly close this issue.

**Comment by bjnhur** [comment]
OK. I see. I'll close it. Thank you for your good interest. ;)
